/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.Controlador;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import projetoes1.Aluno;
import projetoes1.Exercicio;
import projetoes1.RotinaAluno;

/**
 *
 * @author JOÃO VICTOR
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    private void completar(){
    Controlador control = new Controlador();
       ArrayList<Aluno> aluno = control.obterAlunos();
       DefaultTableModel model = (DefaultTableModel) tabela1.getModel();
       if(aluno != null){    
           for(Aluno alunos: aluno){
               Object linha[] = new Object[2];
               linha[0] = alunos.getNome();
               linha[1] = alunos.getCpf();
               model.addRow(linha);
        }
           }
       }
    
    private void completarExercicios(){
    Controlador control = new Controlador();
       ArrayList<Exercicio> exercicios = control.obterExercicios();
       DefaultTableModel model = (DefaultTableModel) tabela2.getModel();
       if(exercicios != null){    
           for(Exercicio exercicio: exercicios){
               Object linha[] = new Object[3];
               linha[0] = exercicio.getNome();
               linha[1] = exercicio.getTipo();
               linha[2] = exercicio.getDescricao();
               model.addRow(linha);
        }
           }
       }
    private void completarRotina(RotinaAluno rotina){
        ArrayList<Exercicio> exercicios = rotina.getExercicios();
        ArrayList<String> serie = null;
        serie=rotina.getSerie();
        System.out.println(serie.size());
       DefaultTableModel model = (DefaultTableModel) tabelarot.getModel();
       if(exercicios != null){    
           for(int i=0;i<exercicios.size();i++){
               Object linha[] = new Object[3];
               linha[0] = exercicios.get(i).getNome();
               linha[1] = exercicios.get(i).getTipo();
               if(serie.size()>0)
               linha[2] = serie.get(i);
               model.addRow(linha);
        }
           }
       }
    
    private void completarRotinaAlu(ArrayList<Exercicio> exercicios,ArrayList<String> serie){
       DefaultTableModel model = (DefaultTableModel) tabelarotinaaluno.getModel();
       int i=0;
       if(exercicios != null){    
           for(Exercicio exercicio: exercicios){
               Object linha[] = new Object[3];
               linha[0] = exercicio.getNome();
               linha[1] = exercicio.getTipo();
               linha[2] = serie.get(i);
               model.addRow(linha);
               i++;
        }
           }
       }
    
    private void removerTabelaAlunos(){
       DefaultTableModel model = (DefaultTableModel) tabela1.getModel();
       int tam = tabela1.getRowCount();
       for(int i=0; i<tam; i++){
           model.removeRow(0);
       }
    }
    private void removerTabelaExercicios(){
       DefaultTableModel model = (DefaultTableModel) tabela2.getModel();
       int tam = tabela2.getRowCount();
       for(int i=0; i<tam; i++){
           model.removeRow(0);
       }
    }
       private void removerTabelaRotina(){
       DefaultTableModel model = (DefaultTableModel) tabelarot.getModel();
       int tam = tabelarot.getRowCount();
       for(int i=0; i<tam; i++){
           model.removeRow(0);
       }
    }
       private void removerTabelaRotinaAlu(){
       DefaultTableModel model = (DefaultTableModel) tabelarotinaaluno.getModel();
       int tam = tabelarotinaaluno.getRowCount();
       for(int i=0; i<tam; i++){
           model.removeRow(0);
       }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        root = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btalu = new javax.swing.JRadioButton();
        btadd = new javax.swing.JRadioButton();
        btrot = new javax.swing.JRadioButton();
        criarExer = new javax.swing.JRadioButton();
        aturot = new javax.swing.JRadioButton();
        btnexer = new javax.swing.JRadioButton();
        root2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        alunome = new javax.swing.JTextField();
        alucpf = new javax.swing.JTextField();
        aluid = new javax.swing.JTextField();
        alusenha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddAluno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nomeex = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipoex = new javax.swing.JTextField();
        descex = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btncriarex = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        btnpassar = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        rotcpf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnprocurar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        cpfrot = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelarot = new javax.swing.JTable();
        btnconserie = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelarotinaaluno = new javax.swing.JTable();
        btnsairusu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        root.setLayout(new java.awt.CardLayout());

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        login.setToolTipText("login");

        jLabel1.setText("login:");

        jLabel2.setText("senha:");

        senha.setToolTipText("senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(entrar)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addComponent(senha))
                .addGap(248, 248, 248))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(entrar)
                .addGap(114, 114, 114))
        );

        root.add(jPanel2, "card2");

        btg1.add(btalu);
        btalu.setText("Alunos");
        btalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaluActionPerformed(evt);
            }
        });

        btg1.add(btadd);
        btadd.setText("Adicionar Alunos");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btg1.add(btrot);
        btrot.setText("Ver Rotina");
        btrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrotActionPerformed(evt);
            }
        });

        btg1.add(criarExer);
        criarExer.setText("Criar exercicio");
        criarExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarExerActionPerformed(evt);
            }
        });

        btg1.add(aturot);
        aturot.setText("Atualizar Rotina");
        aturot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aturotActionPerformed(evt);
            }
        });

        btg1.add(btnexer);
        btnexer.setText("Exercicios");
        btnexer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexerActionPerformed(evt);
            }
        });

        root2.setLayout(new java.awt.CardLayout());

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        root2.add(jPanel4, "card2");

        jLabel3.setText("Nome:");

        jLabel4.setText("CPF:");

        jLabel5.setText("Id:");

        jLabel6.setText("Senha:");

        AddAluno.setText("Adicionar");
        AddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alunome)
                            .addComponent(alucpf)
                            .addComponent(aluid)
                            .addComponent(alusenha, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addComponent(AddAluno))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alunome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alucpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aluid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alusenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addComponent(AddAluno)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        root2.add(jPanel5, "card3");

        jLabel7.setText("Nome:");

        jLabel8.setText("Tipo:");

        jLabel9.setText("Descrição");

        btncriarex.setText("Criar");
        btncriarex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncriarexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncriarex, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descex, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(nomeex)
                            .addComponent(tipoex))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tipoex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(45, 45, 45)
                .addComponent(btncriarex)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        root2.add(jPanel3, "card4");

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        root2.add(jPanel6, "card5");

        jScrollPane3.setViewportView(list1);

        jScrollPane4.setViewportView(list2);

        btnpassar.setText("Passar>>");
        btnpassar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpassarActionPerformed(evt);
            }
        });

        btnvoltar.setText("<<Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        jLabel10.setText("CPF:");

        btnprocurar.setText("Procurar");
        btnprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocurarActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnvoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpassar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(rotcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnprocurar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnprocurar))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnpassar)
                        .addGap(31, 31, 31)
                        .addComponent(btnvoltar)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        root2.add(jPanel7, "card6");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("CPF:");

        tabelarot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Serie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelarot);

        btnconserie.setText("Confirmar serie");
        btnconserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconserieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cpfrot, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnconserie))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnconserie)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        root2.add(jPanel8, "card7");

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(root2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btalu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btrot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(criarExer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aturot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btalu)
                    .addComponent(btadd)
                    .addComponent(btrot)
                    .addComponent(criarExer)
                    .addComponent(aturot)
                    .addComponent(btnexer)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(root2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        root.add(jPanel1, "card3");

        tabelarotinaaluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Serie"
            }
        ));
        jScrollPane6.setViewportView(tabelarotinaaluno);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        btnsairusu.setText("Sair");
        btnsairusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairusuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsairusu)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsairusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        root.add(jPanel9, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        if(login.getText().equals("admin") && senha.getText().equals("admin")){
            CardLayout c = (CardLayout) root.getLayout();
                c.show(root, "card3");
                login.setText("");
                senha.setText("");
                removerTabelaAlunos();
                completar();
        }
        else{
            int cpf = control.buscarLogin(login.getText(), senha.getText());
            if(cpf >=0){
                CardLayout c = (CardLayout) root.getLayout();
                c.show(root, "card4");
                RotinaAluno rotina = control.obterRotina(cpf);
                removerTabelaRotinaAlu();
                completarRotinaAlu(rotina.getExercicios(),rotina.getSerie());
                control.addRotina(rotina);
            }
        }
    }//GEN-LAST:event_entrarActionPerformed

    private void btaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaluActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root2.getLayout();
        c.show(root2, "card2");
        removerTabelaAlunos();
        completar();
    }//GEN-LAST:event_btaluActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root2.getLayout();
        c.show(root2, "card3");
    }//GEN-LAST:event_btaddActionPerformed

    private void AddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAlunoActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        String nome,senha,id;
        int cpf;
        nome = alunome.getText();
        cpf = Integer.parseInt(alucpf.getText());
        senha = alusenha.getText();
        id = aluid.getText();
        control.addAluno(nome, id, senha, cpf);
        alunome.setText("");
        alucpf.setText("");
        alusenha.setText("");
        aluid.setText("");
    }//GEN-LAST:event_AddAlunoActionPerformed

    private void criarExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarExerActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root2.getLayout();
        c.show(root2, "card4");
    }//GEN-LAST:event_criarExerActionPerformed

    private void btncriarexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncriarexActionPerformed
        // TODO add your handling code here:
        String nome,desc;
        char tipo;
        nome = nomeex.getText();
        desc = descex.getText();
        tipo = tipoex.getText().charAt(0);
        Controlador control = new Controlador();
        control.addExercicio(nome, tipo, desc);
        nomeex.setText("");
        descex.setText("");
        tipoex.setText("");
    }//GEN-LAST:event_btncriarexActionPerformed

    private void btnexerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexerActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root2.getLayout();
        c.show(root2, "card5");
        removerTabelaExercicios();
        completarExercicios();
    }//GEN-LAST:event_btnexerActionPerformed

    private void aturotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aturotActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root2.getLayout();
        c.show(root2, "card6");
    }//GEN-LAST:event_aturotActionPerformed

    private boolean verExercicioIgual(Exercicio ex,ArrayList<Exercicio> exs){
        for(Exercicio exr: exs){
            if(exr.getNome().equals(ex.getNome())){
                return false;
            }
        }
        return true;
    }
    DefaultListModel<String> list = new DefaultListModel();
        DefaultListModel<String> lista2 = new DefaultListModel();
        
    private void btnprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocurarActionPerformed
        // TODO add your handling code here:
        list.clear();
        lista2.clear();
        Controlador control = new Controlador();
        int cpf = Integer.parseInt(rotcpf.getText());
        RotinaAluno rotina = control.obterRotina(cpf);
        if(rotina == null){
            rotina = null;
        }
        else{
       if(rotina.getExercicios()!= null){
           for(Exercicio exercicio: rotina.getExercicios()){
                   String msg = exercicio.getNome();
                   list.addElement(msg);
           }
       }}
       ArrayList<Exercicio> exercicios = control.obterExercicios();
       if(exercicios!= null){
           for(Exercicio exercicio: exercicios){
                if(rotina!=null){
                   if(verExercicioIgual(exercicio,rotina.getExercicios())==true){
                   String msg2 = exercicio.getNome();
                   lista2.addElement(msg2);
                   }
                }
                else{
                    String msg2 = exercicio.getNome();
                   lista2.addElement(msg2);
                }
           }
       }
       list1.setModel(lista2);
       list2.setModel(list);
        //control.addRotina(rotina);
    }//GEN-LAST:event_btnprocurarActionPerformed

    private void btnpassarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpassarActionPerformed
        // TODO add your handling code here:
        if(list1.getSelectedValue()!=null){
        list.addElement(list1.getSelectedValue());
        lista2.remove(list1.getSelectedIndex());
        list2.setModel(list);
        }
    }//GEN-LAST:event_btnpassarActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        if(list2.getSelectedValue()!=null){
        lista2.addElement(list2.getSelectedValue());
        list.remove(list2.getSelectedIndex());
        list1.setModel(lista2);
        }
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String msg;
        Exercicio exercicio;
        RotinaAluno rotina = new RotinaAluno();
        Controlador control = new Controlador();
        ArrayList<Exercicio> exercicios = new ArrayList();
        for(int i=0;i<list.getSize();i++){
            msg = list.getElementAt(i);
            exercicio = control.obterExercicio(msg);
            exercicios.add(exercicio);
                }
        msg = rotcpf.getText();
        //RotinaAluno rot=control.obterRotina(Integer.parseInt(msg));
        rotina.setCpf(Integer.parseInt(msg));
        rotina.setExercicios(exercicios);
        control.addRotina(rotina);
        list.clear();
        lista2.clear();
        rotcpf.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrotActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root2.getLayout();
        c.show(root2, "card7");
        cpfrot.setText("");
        removerTabelaRotina();
    }//GEN-LAST:event_btrotActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        int cpf = Integer.parseInt(cpfrot.getText());
        RotinaAluno rotina = control.obterRotina(cpf);
        removerTabelaRotina();
        completarRotina(rotina);
        control.addRotina(rotina);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root.getLayout();
                c.show(root, "card2");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnconserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconserieActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelarot.getModel();    
        String msg; 
        ArrayList<String> serie =new ArrayList();
        for(int i=0;i<model.getRowCount();i++){
               cpfrot.setFocusable(true);
               msg = (String) model.getValueAt(i, 2);
               serie.add(msg);
        }
        Controlador control = new Controlador();
        int cpf = Integer.parseInt(cpfrot.getText());
        RotinaAluno rotina = control.obterRotina(cpf);
        rotina.setSerie(serie);
        control.addRotina(rotina);
    }//GEN-LAST:event_btnconserieActionPerformed

    private void btnsairusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairusuActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) root.getLayout();
                c.show(root, "card2");
    }//GEN-LAST:event_btnsairusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAluno;
    private javax.swing.JTextField alucpf;
    private javax.swing.JTextField aluid;
    private javax.swing.JTextField alunome;
    private javax.swing.JTextField alusenha;
    private javax.swing.JRadioButton aturot;
    private javax.swing.JRadioButton btadd;
    private javax.swing.JRadioButton btalu;
    private javax.swing.ButtonGroup btg1;
    private javax.swing.JButton btnconserie;
    private javax.swing.JButton btncriarex;
    private javax.swing.JRadioButton btnexer;
    private javax.swing.JButton btnpassar;
    private javax.swing.JButton btnprocurar;
    private javax.swing.JButton btnsairusu;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JRadioButton btrot;
    private javax.swing.JTextField cpfrot;
    private javax.swing.JRadioButton criarExer;
    private javax.swing.JTextField descex;
    private javax.swing.JButton entrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nomeex;
    private javax.swing.JPanel root;
    private javax.swing.JPanel root2;
    private javax.swing.JTextField rotcpf;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTable tabela1;
    private javax.swing.JTable tabela2;
    private javax.swing.JTable tabelarot;
    private javax.swing.JTable tabelarotinaaluno;
    private javax.swing.JTextField tipoex;
    // End of variables declaration//GEN-END:variables
}
